name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update version in metadata.json
        run: |
          # Extract version and remove 'v' prefix if present
          VERSION_WITHOUT_V=${{ github.ref_name }}
          VERSION_WITHOUT_V=${VERSION_WITHOUT_V#v}

          # Update version in metadata.json
          jq --arg ver "$VERSION_WITHOUT_V" '.versions[0].version = $ver' metadata.json > metadata.json.tmp
          mv metadata.json.tmp metadata.json

      - name: Create ZIP archive
        id: create_archive
        run: |
          echo "archive_name=${{ github.ref_name }}.zip" >> $GITHUB_OUTPUT
          
          zip -r "${{ github.ref_name }}.zip" \
            3dmodels/ \
            footprints/ \
            symbols/ \
            metadata.json \
            -x "*.git*" -x "*.github*"

      - name: Upload archive to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} ${{ steps.create_archive.outputs.archive_name }} --clobber